version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Training model..."
      - python scripts/train.py
      - echo "Deploying model..."
      - python scripts/model-deploy.py
